#!/bin/bash

# OPT_COMMIT_ID
# OPT_CLIENT_ID

# OPT_DD_COUNT
# OPT_DD_FILENAME

# OPT_GPG_KEY

# OPT_S3_BUCKET


# [Bash safe mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/)
IFS=$'\n\t'
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OPT_DD_SKIP=0 OPT_DD_BS=1 OPT_IS_LAST=1 OPT_S3_OBJECT="c-${OPT_COMMIT_ID}-${OPT_CLIENT_ID}.commit" ${DIR}/test-upload-s3
