#!/bin/bash

# OPT_SHA
# OPT_PART

# OPT_DD_SKIP
# OPT_DD_BS
# OPT_DD_COUNT
# OPT_DD_FILENAME

# OPT_GPG_KEY

# OPT_S3_BUCKET

# OPT_IS_LAST

# [Bash safe mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/)
IFS=$'\n\t'
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OPT_S3_OBJECT="f-${OPT_SHA}-${OPT_PART}.ebak" ${DIR}/upload-cat
